
FROM openjdk:17-oracle

MAINTAINER maintainer <disney.medina27@email.com>
ENV DEVICE_DIR=/app
ENV DEVICE_JAR=/target/Grupo07-0.0.1-SNAPSHOT-spring-boot.jar
COPY ${DEVICE_JAR} ${DEVICE_DIR}/${DEVICE_JAR}




# Expone el puerto en el que la aplicación se ejecutará
#EXPOSE 8095

#CMD ["java", "-jar", "Grupo07-0.0.1-SNAPSHOT-spring-boot.jar"]

